---
deployment:
 tasks:
    - export DEPLOYPATH=/home/robexhrv/public_html/projects/colorstella
    - /bin/cp -R /home/robexhrv/WheelyGoodChoices/build/static $DEPLOYPATH
    - /bin/cp /home/robexhrv/WheelyGoodChoices/build/asset-manifest.json $DEPLOYPATH
    - /bin/cp /home/robexhrv/WheelyGoodChoices/build/favicon.ico $DEPLOYPATH
    - /bin/cp /home/robexhrv/WheelyGoodChoices/build/index.html $DEPLOYPATH
    - /bin/cp /home/robexhrv/WheelyGoodChoices/build/manifest.json $DEPLOYPATH
    - /bin/cp /home/robexhrv/WheelyGoodChoices/build/robots.txt $DEPLOYPATH
    - /bin/cp /home/robexhrv/WheelyGoodChoices/build/android-chrome-192x192.png $DEPLOYPATH
    - /bin/cp /home/robexhrv/WheelyGoodChoices/build/android-chrome-512x512.png $DEPLOYPATH
    - /bin/cp /home/robexhrv/WheelyGoodChoices/build/favicon-32x32.png $DEPLOYPATH
    - /bin/cp /home/robexhrv/WheelyGoodChoices/build/favicon-16x16.png $DEPLOYPATH
    - /bin/cp /home/robexhrv/WheelyGoodChoices/build/apple-touch-icon.png $DEPLOYPATH